// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGqrCy-AGao_T7vWZhjMrVd5JMx5SXaCQ',
    appId: '1:278187835342:web:8c3661fa87b7b30dcb359f',
    messagingSenderId: '278187835342',
    projectId: 'reusemart-app-965a3',
    authDomain: 'reusemart-app-965a3.firebaseapp.com',
    storageBucket: 'reusemart-app-965a3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4MHjIZl1JDVeC_IGEx9lU8CXG1_EZQ7c',
    appId: '1:278187835342:android:658b5461ea9dc190cb359f',
    messagingSenderId: '278187835342',
    projectId: 'reusemart-app-965a3',
    storageBucket: 'reusemart-app-965a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtktNvL1lMEnLVBzAYea3WWhfNtnifqTc',
    appId: '1:278187835342:ios:20199b5b8f83a827cb359f',
    messagingSenderId: '278187835342',
    projectId: 'reusemart-app-965a3',
    storageBucket: 'reusemart-app-965a3.firebasestorage.app',
    iosBundleId: 'com.example.p3lcoba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtktNvL1lMEnLVBzAYea3WWhfNtnifqTc',
    appId: '1:278187835342:ios:20199b5b8f83a827cb359f',
    messagingSenderId: '278187835342',
    projectId: 'reusemart-app-965a3',
    storageBucket: 'reusemart-app-965a3.firebasestorage.app',
    iosBundleId: 'com.example.p3lcoba',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGqrCy-AGao_T7vWZhjMrVd5JMx5SXaCQ',
    appId: '1:278187835342:web:6d6976b7350e5d91cb359f',
    messagingSenderId: '278187835342',
    projectId: 'reusemart-app-965a3',
    authDomain: 'reusemart-app-965a3.firebaseapp.com',
    storageBucket: 'reusemart-app-965a3.firebasestorage.app',
  );
}
